<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class DepartmentSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('departments')->truncate();

        $now = Carbon::now();

        DB::table('departments')->insert([

            // ── ARTS FACULTY ───────────────────────────────────────────────────────

            [
                'slug'              => 'english',
                'name'              => 'Department of English',
                'faculty_group'     => 'arts',
                'icon'              => 'fa-book-open',
                'color'             => 'blue',
                'established_year'  => 1979,
                'about'             => 'The Department of English was established in 1979 with a mission to create passion for English amongst the learners and empowerment of successful communication, and to teach human values by learning world classics. The department offers undergraduate programmes in English up to the second year level and has two teaching staff. The department offers a "Basic English Grammar Certificate Course" and maintains a separate departmental library with textbooks and reference books made available to learners. The department arranges guest lectures by eminent personalities from various fields for enhancement of communication skills and organises various programmes and competitions. The department participates enthusiastically in all co-curricular and extra-curricular activities conducted by various committees of the college.',
                'vision'            => 'To create passion for English amongst learners and empower successful communication by teaching human values through world classics.',
                'mission'           => 'To provide quality education in English language and literature, fostering communication skills and appreciation for literary traditions.',
                'goals'             => null,
                'highlights'        => json_encode([
                    'Basic English Grammar Certificate Course',
                    'Separate departmental library with textbooks and reference books',
                    'Regular guest lectures by eminent personalities from various fields',
                    'Active participation in co-curricular and extra-curricular activities',
                    'Programmes and competitions for enhancement of communication skills',
                ]),
                'programmes_offered' => json_encode([
                    ['class' => 'F.Y.B.A.', 'subject' => 'Communication Skills in English-I', 'type' => 'AEC', 'credits' => 2],
                    ['class' => 'F.Y.B.A.', 'subject' => 'Introduction to Literatures in English-I', 'type' => 'Major/Minor', 'credits' => 4],
                    ['class' => 'F.Y.B.Com', 'subject' => 'Business Communication Skills-I', 'type' => 'AEC', 'credits' => 2],
                    ['class' => 'F.Y.B.Com', 'subject' => 'Indian Short Stories', 'type' => 'O.E.', 'credits' => 2],
                    ['class' => 'F.Y.B.Sc', 'subject' => 'Introduction to Communication Skills in English-I', 'type' => 'AEC', 'credits' => 2],
                    ['class' => 'S.Y.B.A.', 'subject' => 'Introduction to Forms of Literature: Drama', 'type' => 'Major/Minor', 'credits' => 4],
                    ['class' => 'S.Y.B.A.', 'subject' => 'Introduction to Forms of Literature: Novel', 'type' => 'Major/Minor', 'credits' => 4],
                    ['class' => 'S.Y.B.A.', 'subject' => 'Communication Skills in English-II', 'type' => 'AEC', 'credits' => 2],
                ]),
                'intake_ug'         => null,
                'intake_pg'         => null,
                'has_phd'           => false,
                'hod_name'          => 'Dr. Ganpati Pandurang Mulik',
                'is_active'         => true,
                'order'             => 1,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            [
                'slug'              => 'marathi',
                'name'              => 'Department of Marathi',
                'faculty_group'     => 'arts',
                'icon'              => 'fa-feather-alt',
                'color'             => 'orange',
                'established_year'  => 1983,
                'about'             => 'The Department of Marathi was established in 1983. With a proud tradition of 43 years, the department continuously runs student-centric programmes for academic, research, cultural, and language skill development. The department was founded by litterateur and journalist Late Dr. Madhav Potdar, who was its first Head. Subsequently, Dr. Vinaya Bhandari and Prof. Mohan Ballal made valuable contributions to its progress. The department teaches Marathi language and literature papers for F.Y. and S.Y. Arts, Commerce, Science and Computer classes. T.Y.B.A. (Marathi Major) degree has six papers. Since 2024-25, under NEP, students from other streams can also study Marathi and related skills. The department has launched a "Journalism and Mass Communication Certificate Course" to provide career opportunities in media.',
                'vision'            => 'To create awareness among students that the study of language and literature is important for the overall development of human culture; to develop confidence that society\'s intellectual direction can be refined through the interrelationship of language, literature, culture and society; and to reveal the connection of Marathi language and literature study with other languages and knowledge disciplines.',
                'mission'           => 'To create responsible citizens through language and literature study; to provide awareness of the scope of language and literature study and career opportunities within it, thereby producing mature scholars, critics, artists, and researchers.',
                'goals'             => 'To create awareness of society and culture through literary study; to consolidate the directions of social equality and cultural development; to raise awareness and activism so that Marathi language becomes a language of knowledge; to develop linguistic skill capacity of students studying Marathi language and literature including translation, comparative literature, and writing skills for various media.',
                'highlights'        => json_encode([
                    'Journalism and Mass Communication Certificate Course',
                    'Reading Inspiration Day, Marathi Language Fortnight, Marathi Language Pride Day',
                    'Author Visit Programme — "Lekhak Aaplya Bhetila"',
                    'Oratory and Writing Workshops — "Vaktrutva va Lekhan Karyashala"',
                    'Guest lectures by eminent litterateurs, critics, and journalists',
                    'Students have won gold medals at university level in Marathi',
                    'Alumni working as professors, teachers, lawyers, journalists, and in government services',
                ]),
                'programmes_offered' => json_encode([
                    ['class' => 'F.Y.B.A.', 'subject' => 'Marathi (Major)', 'type' => 'Major', 'credits' => 4],
                    ['class' => 'F.Y.B.A.', 'subject' => 'Marathi AEC — Writing Skills for Print Media', 'type' => 'AEC', 'credits' => 2],
                    ['class' => 'S.Y.B.A.', 'subject' => 'Marathi Major — Sem III & IV', 'type' => 'Major', 'credits' => 4],
                    ['class' => 'S.Y.B.A.', 'subject' => 'Marathi AEC — Translation Skills', 'type' => 'AEC', 'credits' => 2],
                    ['class' => 'S.Y.B.A.', 'subject' => 'Marathi VSC — Digitisation', 'type' => 'VSC', 'credits' => 2],
                    ['class' => 'T.Y.B.A.', 'subject' => 'Marathi Major (6 papers)', 'type' => 'Major', 'credits' => 4],
                ]),
                'intake_ug'         => null,
                'intake_pg'         => null,
                'has_phd'           => false,
                'hod_name'          => 'Dr. Bhausaheb M. Nannaware',
                'is_active'         => true,
                'order'             => 2,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            [
                'slug'              => 'economics',
                'name'              => 'Department of Economics',
                'faculty_group'     => 'arts',
                'icon'              => 'fa-chart-line',
                'color'             => 'green',
                'established_year'  => 1979,
                'about'             => 'The Department of Economics was established in 1979 with a vision to promote academic excellence and economic awareness among students. The department focuses on teaching Economics in a simple, practical, and research-oriented manner so that students can understand economic issues at local, national, and global levels. It provides opportunities for skill development through academic activities, seminars, workshops, and field-based learning. The department honours its former Heads Late Dr. B.D. Bansode, Late Prof. R.P. Kothawale (author of Maharashtra\'s First Economics SET guidance book) and Dr. V.S. Kulkarni, whose legacy continues to inspire. The department also supports students in building careers in higher education, banking, finance, corporate sectors, entrepreneurship, and public services.',
                'vision'            => 'To promote academic excellence and economic awareness so that students can understand economic issues at local, national, and global levels.',
                'mission'           => 'To teach Economics in a simple, practical, and research-oriented manner while providing skill development through seminars, workshops, and field-based learning.',
                'goals'             => null,
                'highlights'        => json_encode([
                    'Share market training and financial literacy sessions for students',
                    'Field visits, on-job training, and project-based learning',
                    'Mr. Rupesh Shid — NET-JRF qualified, currently pursuing Ph.D. at IIT Bombay',
                    'Faculty research published in international journals',
                    'BCUD, University of Mumbai funded research projects',
                    'Innovative use of presentations, group discussions, and case studies',
                    'NEP 2020 compliant — multidisciplinary and skill-based learning',
                ]),
                'programmes_offered' => json_encode([
                    ['class' => 'F.Y.B.A.', 'subject' => 'Economics (Major)', 'type' => 'Major', 'credits' => 4],
                    ['class' => 'F.Y.B.A.', 'subject' => 'VSC Economics', 'type' => 'VSC', 'credits' => 2],
                    ['class' => 'F.Y.B.A.', 'subject' => 'SEC Economics', 'type' => 'SEC', 'credits' => 2],
                    ['class' => 'F.Y.B.Sc/B.Com/BBI/BAF', 'subject' => 'OE Economics', 'type' => 'Open Elective', 'credits' => 2],
                    ['class' => 'S.Y.B.A.', 'subject' => 'Economics (Major) Sem III & IV', 'type' => 'Major', 'credits' => 4],
                    ['class' => 'T.Y.B.A.', 'subject' => 'Economics (Major)', 'type' => 'Major', 'credits' => 4],
                ]),
                'intake_ug'         => null,
                'intake_pg'         => null,
                'has_phd'           => false,
                'hod_name'          => 'Mr. Sanjay Rama Dayare',
                'is_active'         => true,
                'order'             => 3,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            [
                'slug'              => 'sociology-rural-studies',
                'name'              => 'Department of Sociology & Rural Studies',
                'faculty_group'     => 'arts',
                'icon'              => 'fa-users',
                'color'             => 'teal',
                'established_year'  => 1988,
                'about'             => 'The Sociology & Rural Studies Department at KMC College, Khopoli, was established in 1988 with the vision of providing students with a deep understanding of the socio-cultural and economic realities of rural India. The department focuses on equipping students with the knowledge and skills needed to analyse and address the challenges faced by rural communities, along with the broader dynamics of society. Over the years, it has become an essential academic pillar for students seeking to engage with rural development and social issues. The department is equipped with a well-stocked library, offering books, journals, and research papers on sociology and rural studies. It regularly organises seminars, workshops, and guest lectures to engage students with current research trends and practices.',
                'vision'            => 'To develop well-rounded individuals who can contribute to the development and transformation of rural societies through informed actions and interventions.',
                'mission'           => 'To provide high-quality education that blends theoretical knowledge with practical insights, fostering critical thinking and analytical skills to prepare students for careers in social work, rural development, policy-making, and academia.',
                'goals'             => null,
                'highlights'        => json_encode([
                    'Fieldwork in rural surveys, community projects, and rural development programs',
                    'Social awareness programs, cultural events, debates, and rural development initiatives',
                    'Regular seminars, workshops, and guest lectures on contemporary research',
                    'Departmental library with books, journals, and research papers',
                    'Hands-on approach to understanding practical challenges of rural areas',
                    'Students develop leadership skills and social responsibility',
                ]),
                'programmes_offered' => json_encode([
                    ['class' => 'F.Y.B.A.', 'subject' => 'Sociology', 'type' => 'Minor', 'credits' => 4],
                    ['class' => 'F.Y.B.A.', 'subject' => 'Rural Studies', 'type' => 'Minor', 'credits' => 4],
                    ['class' => 'F.Y.B.Com', 'subject' => 'Rural Studies', 'type' => 'Open Elective', 'credits' => 2],
                    ['class' => 'S.Y.B.A.', 'subject' => 'Sociology', 'type' => 'Minor', 'credits' => 4],
                    ['class' => 'S.Y.B.A.', 'subject' => 'Rural Studies', 'type' => 'Minor', 'credits' => 4],
                ]),
                'intake_ug'         => null,
                'intake_pg'         => null,
                'has_phd'           => false,
                'hod_name'          => 'Dr. Vilas K. Magar',
                'is_active'         => true,
                'order'             => 4,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            [
                'slug'              => 'psychology',
                'name'              => 'Department of Psychology',
                'faculty_group'     => 'arts',
                'icon'              => 'fa-brain',
                'color'             => 'purple',
                'established_year'  => null,
                'about'             => 'The Department of Psychology at KMC College is the only grant-aided undergraduate Psychology department in Raigad district. Students can study Psychology and earn a degree here. Over the years, respected principals and professors such as Late Principal S.S. Bhosale, Late Prof. Umbardand, Vice-Principal Prof. Annasaheb Kore, Principal Dr. Narendra Pawar, and Late Prof. S.K. Kanekar have all contributed to the growth of the department. In today\'s world, student mental health is very important. To support this, the department organises activities like counseling, expert lectures (both online and offline), poster presentations, and visits to mental hospitals. These experiences give students practical knowledge and help them connect classroom learning with real-life psychology. With technology growing fast, new areas like online therapy platforms, counseling apps, and artificial intelligence in mental health are opening up.',
                'vision'            => 'To provide quality psychology education that bridges academic knowledge with practical application, supporting student mental health and preparing graduates for diverse careers.',
                'mission'           => 'To offer the only grant-aided undergraduate psychology programme in Raigad district, equipping students with theoretical knowledge and practical skills through counseling sessions, expert lectures, and field experiences.',
                'goals'             => null,
                'highlights'        => json_encode([
                    'Only grant-aided UG Psychology department in Raigad district',
                    'Counseling sessions for student mental health support',
                    'Expert lectures (online and offline) by eminent psychologists',
                    'Poster presentation activities for applied learning',
                    'Visits to mental hospitals for practical exposure',
                    'Career opportunities in counseling, therapy, corporate HR, research, and NGOs',
                ]),
                'programmes_offered' => json_encode([
                    ['class' => 'F.Y.B.A.', 'subject' => 'Psychology (Major)', 'type' => 'Major', 'credits' => 4],
                    ['class' => 'S.Y.B.A.', 'subject' => 'Psychology (Major) Sem III & IV', 'type' => 'Major', 'credits' => 4],
                    ['class' => 'T.Y.B.A.', 'subject' => 'Psychology (Major)', 'type' => 'Major', 'credits' => 4],
                ]),
                'intake_ug'         => null,
                'intake_pg'         => null,
                'has_phd'           => false,
                'hod_name'          => 'Asst. Prof. Bhise S. A.',
                'is_active'         => true,
                'order'             => 5,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── COMMERCE FACULTY ───────────────────────────────────────────────────

            [
                'slug'              => 'commerce',
                'name'              => 'Department of Commerce',
                'faculty_group'     => 'commerce',
                'icon'              => 'fa-briefcase',
                'color'             => 'indigo',
                'established_year'  => 1979,
                'about'             => 'The Department of Commerce at KMC College, established in 1979, has consistently upheld a tradition of academic excellence and holistic development. Since its inception, the department has played a pivotal role in shaping competent commerce graduates equipped with both theoretical knowledge and practical insights. It began its journey with the Bachelor of Commerce (B.Com) programme, laying a strong foundation in core areas such as Accountancy, Economics, and Business Management. Recognizing the need for advanced learning and specialization, the department introduced the Master of Commerce (M.Com) programme in Advanced Accountancy in 2004, thereby creating opportunities for higher education and research-oriented learning. In alignment with its vision to promote research and innovation, the department established a Ph.D. Research Centre in Commerce (Business Policy and Administration) in the academic year 2024–25. Currently, three research scholars are actively pursuing their doctoral studies. Further strengthening its academic offerings, the department introduced professional undergraduate programmes such as Bachelor of Accounting and Finance (BAF) and Bachelor of Banking and Insurance (BBI) in the academic year 2025–26. Notably, 04 alumni have qualified prestigious NET/SET examinations, 05 have become Chartered Accountants, and several others hold responsible positions in banks, financial institutions, corporate organizations, and various industries. Dr. Vinayak R. Gandal has published a patent: "Blockchain Integrated Computing System For Tamper Resistant Data Management" (Application No: 202641003798, Published 13th Feb 2026).',
                'vision'            => 'To nurture future leaders, entrepreneurs, and researchers who can contribute meaningfully to the economy and society at large through academic rigor, research orientation, skill development, and professional ethics.',
                'mission'           => 'To provide a strong foundation in commerce education blending theoretical knowledge with practical skills, fostering a culture of research, innovation, and professional excellence.',
                'goals'             => null,
                'highlights'        => json_encode([
                    'M.Com. in Advanced Accountancy introduced in 2004',
                    'Ph.D. Research Centre in Commerce (Business Policy & Administration) established 2024-25',
                    'BAF and BBI programmes introduced 2025-26',
                    '4 alumni qualified NET/SET; 5 alumni qualified as Chartered Accountants',
                    'Indian Patent published: Blockchain Data Management System (Feb 2026)',
                    '3 BCUD, University of Mumbai funded research projects',
                    'Faculty publications in Scopus-indexed and UGC-listed journals',
                ]),
                'programmes_offered' => json_encode([
                    ['class' => 'F.Y./S.Y./T.Y.', 'subject' => 'Bachelor of Commerce (B.Com)', 'type' => 'UG', 'credits' => null],
                    ['class' => 'F.Y./S.Y./T.Y.', 'subject' => 'Bachelor of Accounting & Finance (BAF)', 'type' => 'UG', 'credits' => null],
                    ['class' => 'F.Y./S.Y./T.Y.', 'subject' => 'Bachelor of Banking & Insurance (BBI)', 'type' => 'UG', 'credits' => null],
                    ['class' => 'Sem I–IV', 'subject' => 'M.Com. in Advanced Accountancy', 'type' => 'PG', 'credits' => null],
                    ['class' => 'Research', 'subject' => 'Ph.D. in Commerce (Business Policy & Administration)', 'type' => 'Ph.D.', 'credits' => null],
                ]),
                'intake_ug'         => 120,
                'intake_pg'         => 20,
                'has_phd'           => true,
                'hod_name'          => 'Dr. Vinayak R. Gandal',
                'is_active'         => true,
                'order'             => 6,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            // ── SCIENCE FACULTY ────────────────────────────────────────────────────

            [
                'slug'              => 'chemistry',
                'name'              => 'Department of Chemistry',
                'faculty_group'     => 'science',
                'icon'              => 'fa-flask',
                'color'             => 'red',
                'established_year'  => 1979,
                'about'             => 'The Department of Chemistry started in 1979, since the establishment of K.M.C. College. It is one of the largest departments of the college. In its history of 46 years, it has grown considerably. The department is located on the ground floor of Building #2 and has three spacious laboratories. The department offers quality education to students from F.Y.B.Sc. up to post-graduation and Ph.D. The intake capacity of the undergraduate class is 120. The department has two postgraduate programmes — M.Sc. (Organic Chemistry) and M.Sc. (Inorganic Chemistry), with an intake capacity of 10 students for each programme. The Department also offers a Ph.D. (Chemistry) programme with an intake capacity of 6 students. The research laboratory, funded by DST-FIST, is located on the second floor and equipped with Infrared Spectrometer (Shimadzu), Double Beam UV-Visible Spectrophotometer (Shimadzu), Rotary Evaporator (Buchi), and other instruments. These were purchased from a grant received from the Department of Science & Technology (Govt. of India) under the FIST scheme. Presently, four faculty members are recognized guides for Ph.D. (Chemistry) from the University of Mumbai. All faculty are actively involved in research and publish in Scopus-indexed journals of Wiley, Elsevier, Springer, RSC, etc.',
                'vision'            => 'To provide quality chemistry education from undergraduate to Ph.D. level, driven by research and equipped with modern instrumentation to contribute to science and society.',
                'mission'           => 'To nurture students through rigorous academic programmes and state-of-the-art research facilities, producing scholars who can contribute meaningfully to chemistry and allied fields.',
                'goals'             => null,
                'highlights'        => json_encode([
                    'DST-FIST funded research laboratory with IR Spectrometer, UV-Vis Spectrophotometer and Rotary Evaporator',
                    'Three spacious laboratories for UG practical training',
                    'M.Sc. Organic Chemistry and M.Sc. Inorganic Chemistry (intake: 10 each)',
                    'Ph.D. programme with intake of 6 students; 4 faculty recognized as Ph.D. guides',
                    'Research publications in Wiley, Elsevier, Springer, RSC Scopus-indexed journals',
                    'UG intake of 120 students; one of the largest departments of the college',
                ]),
                'programmes_offered' => json_encode([
                    ['class' => 'F.Y./S.Y.B.Sc.', 'subject' => 'B.Sc. Chemistry (Major)', 'type' => 'UG Major', 'credits' => null],
                    ['class' => 'F.Y./S.Y.B.Sc.', 'subject' => 'B.Sc. Chemistry (Minor)', 'type' => 'UG Minor', 'credits' => null],
                    ['class' => 'F.Y.B.A./B.Com.', 'subject' => 'OE Chemistry', 'type' => 'Open Elective', 'credits' => null],
                    ['class' => 'Sem I–IV', 'subject' => 'M.Sc. Organic Chemistry', 'type' => 'PG', 'credits' => null],
                    ['class' => 'Sem I–IV', 'subject' => 'M.Sc. Inorganic Chemistry', 'type' => 'PG', 'credits' => null],
                    ['class' => 'Research', 'subject' => 'Ph.D. in Chemistry', 'type' => 'Ph.D.', 'credits' => null],
                ]),
                'intake_ug'         => 120,
                'intake_pg'         => 20,
                'has_phd'           => true,
                'hod_name'          => 'Dr. Ashokrao B. Patil',
                'is_active'         => true,
                'order'             => 7,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

            [
                'slug'              => 'physics',
                'name'              => 'Department of Physics',
                'faculty_group'     => 'science',
                'icon'              => 'fa-atom',
                'color'             => 'sky',
                'established_year'  => 1979,
                'about'             => 'The Department of Physics at KMC College has been a cornerstone of academic excellence since its inception in 1979, established concurrently with the college itself. Founded by the visionary Head, Prof. L.D. Jundhale, the department has consistently strived to foster a deep understanding and appreciation for the fundamental principles of physics. The department currently has two permanent faculty members and two ad-hoc faculty members, under the leadership of Dr. Deepak Gaikwad (Head UG) and Dr. Revanappa C. Ambar (Head PG). The department offers comprehensive B.Sc. and M.Sc. programmes affiliated with the University of Mumbai. The intake capacity of the undergraduate class is 120. The M.Sc. Physics programme has an intake of 20 students. An application for a Ph.D. programme has been submitted and is anticipated to receive approval. Dr. Revanappa C. Ambar works on Supercapacitor, Gas Sensor, Dye Sensitized Solar Cells, Water splitting, Lithium-ion, Sodium-ion and Sulfur-based batteries, nanomaterials, energy modeling, thin film deposition, materials characterisation, photovoltaic cells, and DFT calculation. He has numerous publications in high-impact factor journals and several international and national patents, and is a Ph.D. guide from the University of Mumbai. All faculty are actively involved in research and publish in Scopus-indexed journals of Wiley, Elsevier, Springer, RSC, etc.',
                'vision'            => 'To foster deep understanding and appreciation for the fundamental principles of physics, advancing research and higher education opportunities for aspiring physicists.',
                'mission'           => 'To deliver comprehensive B.Sc. and M.Sc. programmes while actively contributing to research in emerging areas of physics including nanomaterials, energy storage, and photovoltaic technologies.',
                'goals'             => null,
                'highlights'        => json_encode([
                    'M.Sc. Physics programme (intake: 20 students) affiliated to University of Mumbai',
                    'Ph.D. programme application submitted to University of Mumbai',
                    'Research in supercapacitors, nanomaterials, solar cells, and energy storage by Dr. R.C. Ambar',
                    'International and national patents registered by faculty',
                    'Publications in Scopus-indexed journals — Wiley, Elsevier, Springer, RSC',
                    'UG intake of 120 students; department founded by Prof. L.D. Jundhale (1979)',
                ]),
                'programmes_offered' => json_encode([
                    ['class' => 'F.Y./S.Y.B.Sc.', 'subject' => 'B.Sc. Physics (Major)', 'type' => 'UG Major', 'credits' => null],
                    ['class' => 'F.Y./S.Y.B.Sc.', 'subject' => 'B.Sc. Physics (Minor)', 'type' => 'UG Minor', 'credits' => null],
                    ['class' => 'F.Y.B.Sc.', 'subject' => 'Wonders of Physics (OE)', 'type' => 'Open Elective', 'credits' => null],
                    ['class' => 'S.Y.B.Sc.', 'subject' => 'Astronomy and Space Missions (OE)', 'type' => 'Open Elective', 'credits' => null],
                    ['class' => 'S.Y.B.Sc.', 'subject' => 'Physics in Sports (OE)', 'type' => 'Open Elective', 'credits' => null],
                    ['class' => 'Sem I–IV', 'subject' => 'M.Sc. Physics', 'type' => 'PG', 'credits' => null],
                ]),
                'intake_ug'         => 120,
                'intake_pg'         => 20,
                'has_phd'           => false,
                'hod_name'          => 'Dr. Deepak Gaikwad',
                'is_active'         => true,
                'order'             => 8,
                'created_at'        => $now,
                'updated_at'        => $now,
            ],

        ]);
    }
}
