<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FacultySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('faculty_members')->truncate();

        $now = Carbon::now();

        $faculty = [

            // ── ENGLISH DEPARTMENT ─────────────────────────────────────────────────
            [
                'name'             => 'Dr. Ganpati Pandurang Mulik',
                'designation'      => 'Assistant Professor & Head',
                'department'       => 'english',
                'qualification'    => 'M.A., M.Phil., Ph.D.',
                'specialization'   => 'English Literature & Communication',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Mrs. Meenakshi D. Oswal',
                'designation'      => 'Assistant Professor',
                'department'       => 'english',
                'qualification'    => 'M.A.',
                'specialization'   => 'English Literature',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 2,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── MARATHI DEPARTMENT ─────────────────────────────────────────────────
            [
                'name'             => 'Dr. Bhausaheb M. Nannaware',
                'designation'      => 'Head & Associate Professor',
                'department'       => 'marathi',
                'qualification'    => 'M.A., NET, B.Ed., Ph.D., MCJ',
                'specialization'   => 'Marathi Literature & Journalism',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwdmarathidept_informationforcollegewebsite202627/1. Dr. B. M. Nannawre - Photo.jpeg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Mrs. Priya M. Nerlekar',
                'designation'      => 'Assistant Professor',
                'department'       => 'marathi',
                'qualification'    => 'M.A., NET, SET',
                'specialization'   => 'Marathi Literature',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwdmarathidept_informationforcollegewebsite202627/2. Prof.Priya Nerlekar Mar.Dept..jpeg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 2,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Dr. Pratibha S. Tembe',
                'designation'      => 'Assistant Professor',
                'department'       => 'marathi',
                'qualification'    => 'M.A., SET, Ph.D.',
                'specialization'   => 'Marathi Literature',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwdmarathidept_informationforcollegewebsite202627/3. Dr. Prathibha S. Tembe Mar.Dept..jpeg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 3,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── ECONOMICS DEPARTMENT ───────────────────────────────────────────────
            [
                'name'             => 'Mr. Sanjay Rama Dayare',
                'designation'      => 'Assistant Professor & Head of Department',
                'department'       => 'economics',
                'qualification'    => 'M.A., NET, SET, B.Ed.',
                'specialization'   => 'Economics, Environmental Economics, Higher Education Finance',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => 'Worked as Research Assistant with Prof. Dr. Neeraj Hatekar and Prof. Dr. Satyanarayan Kothe of Mumbai School of Economics and Public Policy, University of Mumbai, for the Panvel Municipal Corporation Environmental Reports (2018–2021). Completed a BCUD-funded project on the Khopoli Municipal Council Environmental Report. Has published research papers in international journals, presented papers at conferences, and contributed to the First-Year Economics textbook of the University of Mumbai.',
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Dr. Pratik Sasane',
                'designation'      => 'Assistant Professor',
                'department'       => 'economics',
                'qualification'    => 'M.A., Ph.D.',
                'specialization'   => 'Economics',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 2,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Mr. Kamalakar M. Hirawa',
                'designation'      => 'Assistant Professor',
                'department'       => 'economics',
                'qualification'    => 'M.A., SET',
                'specialization'   => 'Economics, Infrastructure Development',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 3,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Miss. Rutuja C. Hojage',
                'designation'      => 'Assistant Professor',
                'department'       => 'economics',
                'qualification'    => 'M.A., SET',
                'specialization'   => 'Economics',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 4,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Miss. Riya Jackson',
                'designation'      => 'Assistant Professor',
                'department'       => 'economics',
                'qualification'    => 'M.A., B.Ed.',
                'specialization'   => 'Economics',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 5,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── SOCIOLOGY & RURAL STUDIES DEPARTMENT ───────────────────────────────
            [
                'name'             => 'Dr. Vilas K. Magar',
                'designation'      => 'Assistant Professor & Head',
                'department'       => 'sociology-rural-studies',
                'qualification'    => 'M.A., NET, M.Phil., Ph.D.',
                'specialization'   => 'Sociology, Rural Development, Social Policy',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddearsir/Dr.V.K.Magar Photo.jpg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── PSYCHOLOGY DEPARTMENT ──────────────────────────────────────────────
            [
                'name'             => 'Asst. Prof. Bhise S. A.',
                'designation'      => 'Assistant Professor & Head',
                'department'       => 'psychology',
                'qualification'    => 'M.A., M.Phil., NET',
                'specialization'   => 'Psychology, Counseling',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwdaboutthepsychologydept_/Bhise photo_page-0001.jpg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Asst. Prof. Ruthe R. D.',
                'designation'      => 'Assistant Professor',
                'department'       => 'psychology',
                'qualification'    => 'M.A., RCI Registered Diploma in Counselling',
                'specialization'   => 'Counselling Psychology',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwdaboutthepsychologydept_/Ruthe _page-0001.jpg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 2,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Asst. Prof. Dharpawar Sneha Vishwanath',
                'designation'      => 'Assistant Professor',
                'department'       => 'psychology',
                'qualification'    => 'M.A.',
                'specialization'   => 'Psychology',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwdaboutthepsychologydept_/Sneha_page-0001.jpg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 3,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── COMMERCE DEPARTMENT ────────────────────────────────────────────────
            [
                'name'             => 'Dr. Vinayak R. Gandal',
                'designation'      => 'Associate Professor & Head',
                'department'       => 'commerce',
                'qualification'    => 'M.Com., M.B.A., NET, Ph.D.',
                'specialization'   => 'Commerce, Finance, Security Industry, Consumer Behaviour',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => 'Has published over 20 research papers in international journals, 3 books (LAP Lambert Germany, Ramanshil Publication, Success Publication), and holds an Indian Patent (Application No: 202641003798). Completed 2 BCUD, University of Mumbai funded research projects.',
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Mr. Sunil N. Waghmare',
                'designation'      => 'Assistant Professor',
                'department'       => 'commerce',
                'qualification'    => 'M.Com., B.Ed., NET',
                'specialization'   => 'Commerce',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 2,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Shraddha N. Padwal',
                'designation'      => 'Assistant Professor',
                'department'       => 'commerce',
                'qualification'    => 'M.Com., B.Ed.',
                'specialization'   => 'Commerce',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 3,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Pooja Yadav',
                'designation'      => 'Assistant Professor',
                'department'       => 'commerce',
                'qualification'    => 'M.Com., Dip. MCJ',
                'specialization'   => 'Commerce, Mass Communication',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 4,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Yogita Sonawane',
                'designation'      => 'Assistant Professor',
                'department'       => 'commerce',
                'qualification'    => 'M.Com., B.Ed.',
                'specialization'   => 'Commerce',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 5,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Mr. Nandkumar Mali',
                'designation'      => 'Assistant Professor',
                'department'       => 'commerce',
                'qualification'    => 'M.Com., SET, NET',
                'specialization'   => 'Commerce',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 6,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Mr. Kuldeep Chavhan',
                'designation'      => 'Assistant Professor',
                'department'       => 'commerce',
                'qualification'    => 'M.Com., B.Ed., SET, MA(ECO), LLB',
                'specialization'   => 'Commerce, Law, Economics',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 7,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Reshma Hajare',
                'designation'      => 'Assistant Professor',
                'department'       => 'commerce',
                'qualification'    => 'M.Com.',
                'specialization'   => 'Commerce',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 8,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Riya Jackson Mangan',
                'designation'      => 'Assistant Professor (Business Economics)',
                'department'       => 'commerce',
                'qualification'    => 'M.A. (Eco), B.Ed.',
                'specialization'   => 'Business Economics',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 9,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── CHEMISTRY DEPARTMENT ───────────────────────────────────────────────
            [
                'name'             => 'Dr. Vikas B. Suryawanshi',
                'designation'      => 'Professor & Vice Principal',
                'department'       => 'chemistry',
                'qualification'    => 'M.Sc., M.Phil., B.Ed., Ph.D.',
                'specialization'   => 'Chemistry',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofchemistryinformationandphotos/ABP photo.png',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Dr. Sharad P. Panchgalle',
                'designation'      => 'Associate Professor',
                'department'       => 'chemistry',
                'qualification'    => 'M.Sc., NET, SET, Ph.D.',
                'specialization'   => 'Chemistry',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofchemistryinformationandphotos/SPP.JPG',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 2,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Dr. Ashokrao B. Patil',
                'designation'      => 'Associate Professor & Head (UG)',
                'department'       => 'chemistry',
                'qualification'    => 'M.Sc., B.Ed., Ph.D.',
                'specialization'   => 'Chemistry',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofchemistryinformationandphotos/ABP photo.png',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 3,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Dr. Amol A. Nagargoje',
                'designation'      => 'Associate Professor',
                'department'       => 'chemistry',
                'qualification'    => 'M.Sc., NET, Ph.D.',
                'specialization'   => 'Chemistry',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofchemistryinformationandphotos/AAN.jpeg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 4,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Mr. Shailesh A. Shivade',
                'designation'      => 'Assistant Professor & Head (PG)',
                'department'       => 'chemistry',
                'qualification'    => 'M.Sc., NET, SET, GATE',
                'specialization'   => 'Chemistry',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofchemistryinformationandphotos/Shailesh A. Shivade.png',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 5,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Pinki M. Sharma',
                'designation'      => 'Assistant Professor',
                'department'       => 'chemistry',
                'qualification'    => 'M.Sc., NET, SET',
                'specialization'   => 'Chemistry',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofchemistryinformationandphotos/Pinki M. Sharma photo.jpeg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 6,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Nargees M. Kharkar',
                'designation'      => 'Assistant Professor',
                'department'       => 'chemistry',
                'qualification'    => 'M.Sc., B.Ed.',
                'specialization'   => 'Chemistry',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofchemistryinformationandphotos/Nargees Kharkar photo.jpeg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 7,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Vaishnavi P. Khandekar',
                'designation'      => 'Assistant Professor',
                'department'       => 'chemistry',
                'qualification'    => 'M.Sc.',
                'specialization'   => 'Chemistry',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 8,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Mushira Khan',
                'designation'      => 'Assistant Professor',
                'department'       => 'chemistry',
                'qualification'    => 'M.Sc.',
                'specialization'   => 'Chemistry',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 9,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Nuren Shikalgar',
                'designation'      => 'Assistant Professor',
                'department'       => 'chemistry',
                'qualification'    => 'M.Sc.',
                'specialization'   => 'Chemistry',
                'email'            => null,
                'phone'            => null,
                'photo'            => null,
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 10,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

            // ── PHYSICS DEPARTMENT ─────────────────────────────────────────────────
            [
                'name'             => 'Dr. Deepak Gaikwad',
                'designation'      => 'Associate Professor & Head (UG)',
                'department'       => 'physics',
                'qualification'    => 'M.Sc., Ph.D.',
                'specialization'   => 'Physics',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofphysics/WhatsApp Image 2026-04-29 at 11.47.30.jpeg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 1,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Dr. Revanappa C. Ambar',
                'designation'      => 'Assistant Professor & Head (PG)',
                'department'       => 'physics',
                'qualification'    => 'M.Sc., Ph.D.',
                'specialization'   => 'Nanomaterials, Energy Storage, Supercapacitors, Photovoltaics, DFT',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofphysics/Dr. R C Ambare - Photo.jpg',
                'bio'              => 'Working on Supercapacitor, Gas Sensor, Dye Sensitized Solar Cells, Water splitting, Lithium-ion, Sodium-ion and Sulfur-based batteries, nanomaterials, energy modeling, thin film deposition, materials characterisation, photovoltaic cells, and DFT calculation. Has numerous publications in high-impact factor journals and several international and national patents. Ph.D. guide from Department of Physics, University of Mumbai; two students registered for Ph.D. under his supervision.',
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 2,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Aparna More',
                'designation'      => 'Assistant Professor',
                'department'       => 'physics',
                'qualification'    => 'M.Sc., SET',
                'specialization'   => 'Physics',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofphysics/Ms. Aparana More (Photo).jpeg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 3,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],
            [
                'name'             => 'Ms. Snehal Kambali',
                'designation'      => 'Assistant Professor',
                'department'       => 'physics',
                'qualification'    => 'M.Sc., SET',
                'specialization'   => 'Physics',
                'email'            => null,
                'phone'            => null,
                'photo'            => 'documents/fwddepartmentofphysics/Ms. Snehal Kambali (Photo).jpeg',
                'bio'              => null,
                'experience_years' => 0,
                'is_active'        => true,
                'order'            => 4,
                'created_at'       => $now,
                'updated_at'       => $now,
            ],

        ];

        DB::table('faculty_members')->insert($faculty);
    }
}
